"""
backend/schemas/behavior.py
Step 8 - Behavior and Temporal Analysis schemas.
All motion values are image-space (pixels, px/s) - NOT real-world physical units.
"""
from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


class PrimaryBehavior(str, Enum):
    """Dominant behavior state. Determined by rule-based temporal reasoning over image-space motion."""
    UNKNOWN              = "UNKNOWN"
    STATIONARY           = "STATIONARY"
    MOVING               = "MOVING"
    RAPID_MOVEMENT       = "RAPID_MOVEMENT"
    SUDDEN_MOVEMENT      = "SUDDEN_MOVEMENT"
    PROLONGED_STATIONARY = "PROLONGED_STATIONARY"
    POSSIBLE_FALL        = "POSSIBLE_FALL"


class BehaviorState(BaseModel):
    """
    Per-track behavior snapshot for a single processed frame.
    All image-space motion quantities (velocity, speed, acceleration) are in pixels or
    pixels/second. They are NOT physical real-world values.
    """
    track_id: int = Field(..., description="Persistent track ID from ByteTrack")
    timestamp: float = Field(..., description="Frame timestamp in seconds")
    frame_id: Optional[int] = Field(default=None, description="Frame index")

    # Primary classified state
    primary_behavior: PrimaryBehavior = Field(
        default=PrimaryBehavior.UNKNOWN,
        description="Dominant locomotion state from temporal rule reasoning",
    )

    # Secondary flag overlays - non-exclusive
    flag_rapid_movement: bool = Field(default=False, description="Speed exceeds BEHAVIOR_RUNNING_VELOCITY_THRESHOLD")
    flag_sudden_movement: bool = Field(default=False, description="Acceleration exceeds BEHAVIOR_SUDDEN_ACCELERATION_THRESHOLD")
    flag_direction_change: bool = Field(default=False, description="Heading changed by more than BEHAVIOR_DIRECTION_CHANGE_DEGREES")
    flag_possible_fall: bool = Field(default=False, description="Bbox geometry heuristic suggests fall-like event")

    # Motion quantities (image-space; NOT physical speed)
    image_speed_px_per_s: Optional[float] = Field(default=None, description="Image-space speed magnitude (px/s) - NOT real-world speed")
    image_accel_px_per_s2: Optional[float] = Field(default=None, description="Image-space acceleration magnitude (px/s2) - NOT real-world")
    velocity_x: Optional[float] = Field(default=None, description="Horizontal component of image-space velocity (px/s)")
    velocity_y: Optional[float] = Field(default=None, description="Vertical component of image-space velocity (px/s)")
    heading_degrees: Optional[float] = Field(default=None, description="Movement direction in image space (0-360 deg)")

    # Temporal durations
    stationary_duration_s: float = Field(default=0.0, description="Continuous seconds below stationary displacement threshold")
    behavior_duration_s: float = Field(default=0.0, description="Continuous seconds in current primary_behavior state")

    # Zone context (from Step 6)
    zone_id: Optional[str] = Field(default=None, description="Zone ID if track is confirmed inside a zone")
    zone_name: Optional[str] = Field(default=None, description="Zone human-readable name")
    zone_dwell_s: Optional[float] = Field(default=None, description="Dwell duration inside current zone (seconds)")

    # Depth context (from Step 7, optional)
    relative_depth: Optional[float] = Field(
        default=None,
        description="Relative uncalibrated depth at track contact point. Does NOT represent meters.",
    )
    depth_trend: Optional[str] = Field(
        default=None,
        description="Qualitative depth trend: approaching, receding, or stable. NOT a physical distance.",
    )

    # Evidence metadata
    confirmation_frames: int = Field(default=0, description="Consecutive frames sustaining current primary behavior")
    explanation: str = Field(default="", description="Human-readable explanation of behavior classification")


class BehaviorEventType(str, Enum):
    """Significant threshold-crossing events generated by the BehaviorEngine."""
    STATIONARY_CONFIRMED     = "stationary_confirmed"
    PROLONGED_STATIONARY     = "prolonged_stationary"
    RAPID_MOVEMENT_CONFIRMED = "rapid_movement_confirmed"
    SUDDEN_MOVEMENT          = "sudden_movement"
    DIRECTION_CHANGE         = "direction_change"
    POSSIBLE_FALL            = "possible_fall"
    BEHAVIOR_TRANSITION      = "behavior_transition"


class BehaviorEvent(BaseModel):
    """
    A significant behavioral threshold-crossing event from the BehaviorEngine.
    Follows the IndustrialEvent pattern but carries motion-specific fields.
    """
    event_id: str = Field(..., description="Unique event identifier (UUID string)")
    event_type: BehaviorEventType = Field(..., description="Category of behavioral event")
    timestamp: float = Field(..., description="Frame timestamp when event was generated")
    frame_id: Optional[int] = Field(default=None, description="Frame index")
    track_id: int = Field(..., description="Track ID of the actor involved")
    camera_id: str = Field(default="cam_01", description="Camera feed identifier")
    primary_behavior: PrimaryBehavior = Field(..., description="Behavior state at time of event")
    previous_behavior: Optional[PrimaryBehavior] = Field(default=None, description="Previous state for BEHAVIOR_TRANSITION events")
    severity: str = Field(default="low", description="Severity: low, medium, or high")
    explanation: str = Field(..., description="Human-readable explanation of event generation")
    zone_id: Optional[str] = Field(default=None, description="Zone context if relevant")
    image_speed_px_per_s: Optional[float] = Field(default=None, description="Image-space speed at event time (px/s)")
    stationary_duration_s: Optional[float] = Field(default=None, description="Stationary duration at event time (seconds)")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Supplementary context")
